config/routes.rb
Rails.application.routes.draw do
  get 'photos/index/:id' => 'photos#index', as: 'get_user_photos'
  get 'photos/index'
  get 'user/photos' => 'photos#fetch_comments_on_photos',
      as: 'get_comments_on_photo'
  get 'users/index' => 'users#index'
  get 'user/:id' => 'users#show', as: 'get_user'
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments

  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.where(user_id: params[:id])
    @user = User.find(params[:id])
    if @user && @photos
      respond_to do |format|
        format.html
        format.json { render json: { data: { user: @user, photos: @photos } } }
      end
    end
  end

  def fetch_comments_on_photos
    @comments = Comment.includes(:user).where(photo_id: params[:photoId])
    respond_to do |format|
      format.json { render json: { size: @comments.size, comments: @comments.as_json(include: { user: @user }) } }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('first_name ASC')
    @size = @users.size
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @user_photos = Photo.where(user_id: @user.id)
    @all_users = User.where.not(id: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: { user: @user, user_photos: @user_photos } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top" style="background: #42A5F5">
  <div class="container">
    <nav>
      <%= link_to 'CS 6320', root_path , id: 'logo' %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path, style: 'color: #fff' %></li>
        <li><%= link_to 'Log in', '#', style: 'color: #fff' %></li>
      </ul>
    </nav>
  </div>
</header>
<div class="container push-down">
  <%= yield %>
</div>
<!--<footer class="center footer">-->
  <!--Made with <i class="fa fa-heart heart"></i> by Abhishek Ghosh-->
  <!--<div class="center">-->
    <!--<a href="https://github.com/ghoshabhi"><i class="fa fa-github fa-3x"></i></a>-->
  <!--</div>-->
<!--</footer>-->
</body>
</html>

app/views/photos/index.html.erb
<h1>Photos</h1>
<div class="row">
  <% @photos.each do |photo| %>
      <div
        class="col-lg-4 col-md-4 col-sm-4 col-xs-6 viewPhoto"
        data-photo-id="<%= photo.id %>"
        data-user-id="<%= photo.user.id %>"
        data-toggle="modal"
        data-target="#myModal"
        style="cursor:pointer"
      >
        <p>
          <%= photo.created_at.strftime('%b %d') + "'" + photo.created_at.strftime('%y') + ' at ' + photo.created_at.strftime('%r') %>
        </p>
        <%= image_tag photo.file_name, alt: "#{photo.file_name}", class: 'img-responsive', style: 'height: 300px; width: 300px' %>
      </div>
  <% end %>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <p class="comment-size"></p>
        </div>
        <div class="modal-body">
          <div style="display: flex; flex-direction: column">
            <div width="100%">
              <img src="" class="img-responsive image-preview" style="margin:10px">
            </div>
            <hr>
            <div>
              <h4>Comments:</h4>
              <div id="id1" class="comments-block">
                <!--comments go here-->
              </div>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <a href='#' class="btn btn-default" data-dismiss="modal">Close</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
    $('.viewPhoto').on('click', function (e) {
        e.preventDefault();
        const imageUrl = $(this).find('img').attr('src');
        $.ajax({
            url: "<%= get_comments_on_photo_path %>",
            type: 'get',
            dataType: 'json',
            data: { photoId: $(this).data('photoId') },
            success: function (data) {
                //console.log(JSON.stringify(data, null).replace(/\\/g, ""));
                $('.image-preview').attr('src', imageUrl);
                $('.comment-size').text('Number of Comments: ' + data['size']);
                // console.log(data['comments']);
                //console.log(data['comments'][0].comment_text);
                $('.comments-block').html(" ");
                for(var i = 0; i < parseInt(data['size']); i++) {
                    var comment_text = data['comments'][i].comment_text;
                    var comment_date = data['comments'][i].created_at;
                    comment_date = moment(comment_date).format('MM/DD//YYYY, h:mm a');
                    var comment_by = data['comments'][i].user['first_name'] + ' ' + data['comments'][i].user['last_name'];
                    var user_profile = '/user/' + data['comments'][i].user['id'];
                    //console.log(comment_by + ' | ' + user_profile + ' | ' + comment_text);
                    var html = `
                                <a href='${user_profile}'>${comment_by}</a>: ${comment_text}
                                <b><i class='pull-right'>${comment_date}</i></b>
                                <br/><br/>`;
                    $('.comments-block').append(html);
                }

                $('#myModal').modal('show');
            },
            error: function (err) {
                console.log(err);
            }
        });
    });
</script>

app/views/users/index.html.erb
<h2 class="number">There are <%= pluralize(@size, 'user') %> <i class="fa fa-users"></i></h2>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
      <div class="card">
        <img class="card-img-top" src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif">
        <div class="card-block">
          <h5 class="text-bold username center">
            <%= link_to user.first_name + ' ' + user.last_name, get_user_path(user) %>
          </h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="modal-content col-md-10">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title" id="myModalLabel" style="font-weight: bolder">More About <%= @user.first_name %> ...</h4>
      </div>
      <div class="modal-body">
        <div class="center">
          <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
          <h3 class="media-heading"><%= @user.first_name + ' ' + @user.last_name %></h3>
          <h4 class="media-heading"><%= link_to 'Gallery', get_user_photos_path(@user)  %></h4>
        </div>
        <hr>
        <div>
          <div class="media-heading text-left" style="font-size: large">
            <strong>Bio: </strong><br>
            <%= @user.description %>
          </div>
          <br>
        </div>
      </div>
      <div class="modal-footer">
        <div class="center">
          <%= link_to 'Go Back', root_url, class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <h4>Other Users:</h4>
    <ul>
      <% @all_users.each do |user| %>
        <li style="font-size: large;"><%= link_to user.first_name + ' ' + user.last_name, get_user_path(user) %></li>
      <% end %>
    </ul>
  </div>
</div>